services:
  web_scraping:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py
    environment:
      - PYTHONUNBUFFERED=1
