HOST = "localhost"
PORT = 8000
FULL_HOST = f"http://{HOST}:{PORT}"
SCHEDULE_URL = "https://becycle.cl/clase/{class_id}/"
SCHEDULES_WANTED = []
NOT_ALLOWED_CLASS_TYPE = ["beat"]
DEBUG = False

SCHEDULE_ID_START = 13469
SCHEDULES_LIMIT = 1000
REQUESTS_PER_SECOND = 1
